export interface PayrollContract {
    createdBy: string,
    createdDate:string,
    updatedDate: string,
    updatedBy: string,
    pId: number,
    id: string,
    empId: string,
    ecxId: string,
    dateOfEmployeement: string,
    positionID: string,
    departmentID:string,
    gradeID: string,
    stepID: string,
    branchID: string,
    basicSalary: number,
    bank: string,
    bankBranch: string,
    bankAccountNumber: number,
    tinNumber: string,
    grossEarnings: number,
    taxableAmount: number,
    incomeTax: number,
    netPay:number,
    pensionContribution7: number,
    pensionContribution11: number,
    contractStartDate:string,
    contractEndDate: string,
    payRollEndDate:string,
    payRollStartDate:string,
    status: number,

}
export interface Outsource {
    createdBy: string,
    createdDate:string,
    updatedDate: string,
    updatedBy: string,
    pId: number,
    id: string,
    file: string,
    remark: string,
    amount: number,
    date: string,
    status: number,

}
export interface ContractRegistration {
    createdBy: string,
    createdDate:string,
    updatedDate: string,
    updatedBy: string,
    pId: number,
    adId: string,
    empId: string,
    ecxId: string,
    firstName: string,
    middleName: string,
    lastName: string,
    joinDate:string,
    sex: string,
    dateOfBitrh: string,
    placeOfBith: string,
    martialStatus: string,
    salutation: string,
    nationality: string,
    pensionNo: string,
    imageData: string,
    crime: true,
    crimeDescription: string,
    divisionId: string,
    stepId: string,
    branchId: string,
    position: string,
    startDate: string,
    endDate: string,
    bankId: string,
    bankBranch: string,
    bankAccount: 0,
    tinNumber: string,
    status: number
}

