export interface Allowance {
    createdBy: string,
    createdDate: string,
    updatedDate: string,
    updatedBy: string,
    pId: number,
    id: string,
    allowanceType: string,
    position: string,
    step: string,
    grade: string,
    rate: number,
    ratePercent: number,
    status: number,
    amount:number
}

export interface Deduction {
    createdBy: string,
    createdDate: string,
    updatedDate:string,
    updatedBy: string,
    pId: number,
    id: string,
    empId: string
    deductionType: string,
    file: string,
    remark: string,
    amount: number,
    length: number,
    startDate: Date,
    endDate: Date,
    status: number
}

export interface PayRoll {
    createdBy: string,
    createdDate:string,
    updatedDate: string,
    updatedBy: string,
    pId: number,
    id: string,
    empId: string,
    ecxId: string,
    dateOfEmployeement: string,
    positionID: string,
    departmentID:string,
    gradeID: string,
    stepID: string,
    branchID: string,
    basicSalary: number,
    bank: string,
    bankBranch: string,
    bankAccountNumber: number,
    tinNumber: string,
    hardShipA: number,
    telephoneA: number,
    transportA: number,
    taxExcemptedTA: number,
    housingA: number,
    livingA: number,
    otherTaxA: number,
    overTime: number,
    otDay: number,
    otNight: number,
    otWeekend: number,
    otHoliday: number,
    salaryAdvance: number,
    grossEarnings: number,
    taxableAmount: number,
    incomeTax: number,
    pensionContribution7: number,
    pensionContribution11: number,
    courtAndOtherD: number,
    creditAssociationD: number,
    registrationD: number,
    shareD: number,
    savingForCreditAssD: number,
    savingForHousingD: number,
    loanRefund: number,
    penality: number,
    costShareD: number,
    forStreetChildrenD: number,
    gebetaLehagerD: number,
    absentD:number,
    totalDeduction: number,
    netPay: number,
    amtTransfer: number,
    promotionStatus: string,
    actingStatus: string,
    previousNet: number,
    payRollStartDate:string,
    payRollEndDate: string,
    status: number

}
export interface TempPayroll {
    createdBy: string,
    createdDate:string,
    updatedDate: string,
    updatedBy: string,
    pId: number,
    id: string,
    empId: string,
    ecxId: string,
    dateOfEmployeement: string,
    positionID: string,
    departmentID:string,
    gradeID: string,
    stepID: string,
    branchID: string,
    basicSalary: number,
    bank: string,
    bankBranch: string,
    bankAccountNumber: number,
    tinNumber: string,
    hardShipA: number,
    telephoneA: number,
    transportA: number,
    taxExcemptedTA: number,
    housingA: number,
    livingA: number,
    otherTaxA: number,
    overTime: number,
    otDay: number,
    otNight: number,
    otWeekend: number,
    otHoliday: number,
    salaryAdvance: number,
    grossEarnings: number,
    taxableAmount: number,
    incomeTax: number,
    pensionContribution7: number,
    pensionContribution11: number,
    courtAndOtherD: number,
    creditAssociationD: number,
    registrationD: number,
    shareD: number,
    savingForCreditAssD: number,
    savingForHousingD: number,
    loanRefund: number,
    penality: number,
    costShareD: number,
    forStreetChildrenD: number,
    gebetaLehagerD: number,
    absentD:number,
    totalDeduction: number,
    netPay: number,
    amtTransfer: number,
    promotionStatus: string,
    actingStatus: string,
    previousNet: number,
    payRollStartDate:string,
    payRollEndDate: string,
    status: number

}